### PR TITLE
Feature/webUI

### PR DESCRIPTION
**Pull request by stduhpf**
Added a feature allowing to keep track of ingestion progress, and a simple webui with a progress bar to showcase it.

### CODE REVIEW

**Comment by PotatoSpudowski** [comment]
Hi, Thanks for the pull request.

These are good features. The initial implementation of the webUI is a good start that we can build upon as we go. 

However before we can merge we need to look at a few things
1. Can you please rebase to the main branch? (In order to ensure everything works fine)
2. In the examples folder can we have a folder where the html file can be stored?
3. In the readme if we can add instructions in the readme to run the webui server and the html (Maybe using live server or any other way you prefer) that would be appreciated.

**Comment by stduhpf** [comment]
Done!

**Comment by amitsingh19975** [comment]
Hi @stduhpf, thanks for your pull. request. It will be a great addition to the repo.
We've been trying to use your pull request, but we were getting segmentation faults because of the progress callback. So, we decided to add a progress bar to ingest function so that you don't have to worry about its correctness. On top of it, we add tags so that you can track which progress call is being called.

```python

class MyLogger(Logger):
    def progress(self, tag: ProgressTag, done_size: int, total_size) -> None:
        if tag == ProgressTag.Ingest:
                  # do something
        print(f"[Progress]: {tag} {done_size}/{total_size}", flush=True)

model = Model(..., logger=MyLogger())
```

for the full example look at the [example-logging.py](https://github.com/PotatoSpudowski/fastLLaMa/blob/main/examples/python/example-logging.py)

**Comment by stduhpf** [comment]
The Logger-based solution seems to be better that what I did, should I do a new PR for the webUi only?

**Comment by amitsingh19975** [comment]
No need. You can refactor this code if you think you can do it. Otherwise, you can create a new one if it's unmanageable.

**Review by PotatoSpudowski — APPROVED** [review]
LGTM!

**Comment by PotatoSpudowski** [comment]
@stduhpf we loved your implementation and we decided to build on top of it. Working on making the UI more chat like and updating the web socket server to support relevant features that we have that a chat like application would benefit from. 

Here is the link to the [project](https://github.com/users/PotatoSpudowski/projects/2/views/1) if you're interested  in reading up on it 🤗

**Pull request merged**
